export const ALERTS_STORE_ID = 'ALERTS_STORE_ID'
export const LOCALES_STORE_ID = 'LOCALES_STORE_ID'
export const THEMES_STORE_ID = 'THEMES_STORE_ID'

export const LOCALE_STORAGE_KEY = 'LOCALE_STORAGE_KEY'
export const THEME_STORAGE_KEY = 'THEME_STORAGE_KEY'
